server {
    listen 80;

    # Rutas públicas de auth (login, refresh, verify, etc.)
    location /api/v1/auth/ {
        proxy_pass http://auth-api:8000;
    }

    # Users protegido por auth_request -> otro servicio (iam-api)
    location /api/v1/iam/ {
        if ($http_authorization = "") { return 401; }
        auth_request /_auth;
        # Captura el header X-User-Email que devuelve /_auth
        auth_request_set $auth_email $upstream_http_x_user_email;
        # Reenvía el email al servicio de users
        proxy_set_header X-User-Email $auth_email;
        proxy_pass http://iam-api:8000;
    }

    # Orders protegido por auth_request
    location /api/v1/orders/ {
        if ($http_authorization = "") { return 401; }
        auth_request /_auth;
        proxy_pass http://auth-api:8000;
    }

    # Endpoint interno que realiza la validación del token
    location = /_auth {
        internal;

        proxy_pass http://auth-api:8000/api/v1/auth/verify;
        proxy_pass_request_body off;

        proxy_set_header Content-Length "";
        proxy_set_header Authorization $http_authorization;
    }
}

